apiVersion: operators.coreos.com/v1beta1
kind: Subscription
metadata:
  name: sub-to-pubsubplus-eventbroker-operator
  namespace: operators
spec:
  channel: alpha
  name: pubsubplus-eventbroker-operator
  source: solace-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
