---
apiVersion: pubsubplus.solace.com/v1alpha1
kind: EventBroker
metadata:
  name: test-ha
spec:
  redundancy: true
  developer: true
  tls:
    enabled: false
    serverTlsConfigSecret: example-tls-secret
  monitoring:
    enabled: true
    image: ghcr.io/solacedev/solace_prometheus_exporter
    tag: sol-76199
    imagePullPolicy: Always
    imagePullSecrets:
      - name: regcred